### PR TITLE
Python tool create iam parameters

### PR DESCRIPTION
**Pull request by Vermyndax**
Trying to solve IAM creation/policy issues in this one

### CODE REVIEW

**Comment by Vermyndax** [comment]
Made a huge update to this script. It now requires 3 command line options to run. It requires you to have access to the master payer account to create the budget parameter and access to the authlanding account to update the authlanding user list and create the IAM role parameters.

To do this, you need an ~.aws/credentials file that defines your access keys for both accounts and a header that labels the accounts. You also need to know the KeyId of the KMS key to encrypt the IAM role parameters. This is because we create new IAM role parameters when we create the tenant account.

I'm *sure* there are oversights to this gigantic thing, so please look over it very thoroughly and make sure I did not miss anything. Really need @briankfitzwater to look over it and comment on any oversights.

**Comment by Vermyndax** [comment]
@briankfitzwater Please use pylint with python3, not python2. That'll get a better code rating. But there are still nags that I'll fix today.

**Comment by briankfitzwater** [comment]
I can't validate validate localy:

```
master$ terraform validate

Error: Error loading modules: module authlanding_prod: open .terraform/modules/d0c93a964f7b4273ba96b64575c2a05b: no
such file or directory
```

**Comment by Vermyndax** [comment]
Looks like you need to do a terraform init -backend-config="backend.tfvars"

**Comment by briankfitzwater** [comment]
Cheater...disabling the pylint checks:

```
pylint: disable=W0511
pylint: disable=R0914,R0912,R0915
pylint: disable=C0103
pylint: disable=R1705
```

Looks pretty good, even with all the checks re-enabled:

```
tools$ ~/.pyenv/shims/pylint make_grace_tenant.py 
************* Module make_grace_tenant
make_grace_tenant.py:171:6: W0511: TODO: Probably needs to be a little more robust. Should detect the filename and keep (fixme)
make_grace_tenant.py:44:0: R0914: Too many local variables (26/15) (too-many-locals)
make_grace_tenant.py:176:4: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
make_grace_tenant.py:44:0: R0912: Too many branches (13/12) (too-many-branches)
make_grace_tenant.py:44:0: R0915: Too many statements (216/50) (too-many-statements)
make_grace_tenant.py:389:4: R1705: Unnecessary "else" after "return" (no-else-return)

-------------------------------------------------------------------
Your code has been rated at 9.78/10 (previous run: 10.00/10, -0.22)
```

**Comment by Vermyndax** [comment]
@briankfitzwater sorry try it this way:

`terraform validate -var-file=backend.tfvars`

**Comment by briankfitzwater** [comment]
I had to remove my .terraform directory, and then was able to init.  Working now...

**Comment by briankfitzwater** [comment]
Not sure why the plan calls for creating these users:

```
 + aws_iam_user.iam_users[20]
      id:                    <computed>
      arn:                   <computed>
      force_destroy:         "false"
      name:                  "demotest18"
      path:                  "/"
      unique_id:             <computed>

  + aws_iam_user.iam_users[21]
      id:                    <computed>
      arn:                   <computed>
      force_destroy:         "false"
      name:                  "demotest19"
      path:                  "/"
      unique_id:             <computed>

  + aws_iam_user.iam_users[22]
      id:                    <computed>
      arn:                   <computed>
      force_destroy:         "false"
      name:                  "demouser4"
      path:                  "/"
      unique_id:             <computed>

  + aws_iam_user.iam_users[23]
      id:                    <computed>
      arn:                   <computed>
      force_destroy:         "false"
      name:                  "demotest20"
      path:                  "/"
      unique_id:             <computed>

  + aws_iam_user.iam_users[24]
      id:                    <computed>
      arn:                   <computed>
      force_destroy:         "false"
      name:                  "demouser5"
      path:                  "/"
      unique_id:             <computed>

  + aws_iam_user.iam_users[25]
      id:                    <computed>
      arn:                   <computed>
      force_destroy:         "false"
      name:                  "demotest21"
      path:                  "/"
      unique_id:             <computed>

  + aws_iam_user.iam_users[26]
      id:                    <computed>
      arn:                   <computed>
      force_destroy:         "false"
      name:                  "demotest21"
      path:                  "/"
      unique_id:             <computed>

  + aws_iam_user.iam_users[27]
      id:                    <computed>
      arn:                   <computed>
      force_destroy:         "false"
      name:                  "demotest22"
      path:                  "/"
      unique_id:             <computed>

  + aws_iam_user.iam_users[28]
      id:                    <computed>
      arn:                   <computed>
      force_destroy:         "false"
      name:                  "demouser6"
      path:                  "/"
      unique_id:             <computed>

  + aws_iam_user.iam_users[29]
      id:                    <computed>
      arn:                   <computed>
      force_destroy:         "false"
      name:                  "demotest23"
      path:                  "/"
      unique_id:             <computed>
```

**Comment by Vermyndax** [comment]
Those users were added to the authlanding-user-list parameter during my test runs of the python tool before I checked them in. I did not execute the actual terraform though, so the IAM users were not created.

**Pull request merged**
