### PR TITLE
Iam improvements

### PR DESCRIPTION
**Pull request by Vermyndax**
Sets up basic user management and tenant role management using parameter store.

### CODE REVIEW

**Comment by kishorebabu12** [comment]
@Vermyndax I understand the logic in the code. However, shouldn't we use LNA's instead of SNA's for the user list. All GSA users might not have SNA's. Here's the references from your README notes:

_Create a parameter store object called "authlanding-user-list". Use the list type "StringList" and type the list of SNA usernames, delimited by commas. Do not use spaces.

Create the parameter store objects with these names. Make them a type of StringList and use a comma-delimited set of SNA usernames. Note that the users MUST ALREADY EXIST before you add them to these groups, or AWS and Terraform will fail to create or update the IAM roles for the tenant account._

**Comment by tim20watts** [comment]
Kishore SNA accounts must be used for any administrative purposes such as
provisioning/de-provisioning/management of instances. lna accounts can be
used to log into instances or applications to run non administrative
functions, ie. run reports, gather logs, monitor health...

Thank you in advance,
Timothy E. Watts - IDIHC
Innovation Project Management Office - Innovation Specialist
Office (504) 249-6438 | Cell (985) 237-0782 | timothy.watts@gsa.gov |
www.gsa.gov

**Comment by Vermyndax** [comment]
Actually, the beauty of this approach is that you can literally use any username you want. I just suggested SNA in the readme. You can use LNA or any scheme you like.

**Comment by kishorebabu12** [comment]
@Vermyndax I agree in principle with that approach. But, I am not sure if all tenant users will have SNA accounts. For example, I personally don't have an SNA account (I thought I had one). DS team requested that my Government lead submit a ticket on my behalf to get me an SNA. So, Navin is working on this right now. Similarly, what if a new tenant admin doesn't have a SNA account. Does that mean we don't provision their AWS sub account on GRACE until they open a ticket and get a SNA?

**Comment by tim20watts** [comment]
yes that is what is in the ATO on privileged accounts sections, it must
abide by the ATO!!!!

Thank you in advance,
Timothy E. Watts - IDIHC
Innovation Project Management Office - Innovation Specialist
Office (504) 249-6438 | Cell (985) 237-0782 | timothy.watts@gsa.gov |
www.gsa.gov

**Comment by kishorebabu12** [comment]
@Vermyndax As long as we are talking about IAM SNA's, we are good. Thank you for the clarification. Also, I know there's an access policy out there, which can force users to configure MFA after initial login. We should probably look at attaching this policy to all IAM SNA users (at the least).

**Comment by Vermyndax** [comment]
@kishorebabu12 I'd advocate that we set up MFA for all users. Currently I don't see a way to have Terraform create that device, but I'll keep researching.

**Comment by ManojChalise** [comment]
@Vermyndax @kishorebabu12 At this point LNA username or SNA username is just symbolic . Now what requirement they need to meet to get on-board  like full cleared sna holder or just regular user with gsa long name id is enough is question we need to answer. And that is something we can address on on-board off-boarding work flow and in ssp eventually. We don't need to hold coding aspect for that.

@Vermyndax I didn't like concept of having same user having two different account  with two different privileged level.

**Comment by Vermyndax** [comment]
@ManojChalise I didn't like that concept either, which is why I proposed SNA only ;)

**Comment by tim20watts** [comment]
Manoj you need to Look at the Enterprise Directory Services Rules Set forth
by Security (Tom ). That is going to dictate  how this is going to be
allowed to work, the FISMA owner will set precedence.

Thank you in advance,
Timothy E. Watts - IDIHC
Innovation Project Management Office - Innovation Specialist
Office (504) 249-6438 | Cell (985) 237-0782 | timothy.watts@gsa.gov |
www.gsa.gov

**Comment by ManojChalise** [comment]
@tim20watts Lets take it offline, and spare git comments for code related stuffs.

**Pull request merged**
