### PR TITLE
New iam approach

### PR DESCRIPTION
**Pull request by Vermyndax**
Do not merge yet, please.

### CODE REVIEW

**Comment by kishorebabu12** [comment]
@Vermyndax Can we replace the email notification (in the code) for the two below modules to DevSecOps email ID instead of Aidan's email id?

scp_test
broker_test

**Comment by Vermyndax** [comment]
@kishorebabu12 Nope, sure can't! Remember, we can't change email address properties 👍

**Comment by Vermyndax** [comment]
@kishorebabu12 We need to open another PR to remove that members.tf file from the master branch and manually clean up those accounts anyway.

**Comment by Vermyndax** [comment]
This is now ready for approval and merge. It works, and STS assume policy works. However, I need to add a conditions statement to the roles so we can accept roles by groups

**Pull request merged**
